package data

import (
	"fmt"

	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
)

const schema = `
	CREATE TABLE IF NOT EXISTS tags (
		id integer generated by default as identity,
		name text
	);
`

const connStr = "user=postgres dbname=postgres password=maxim3880 sslmode=disable"

//CreatePostgresDbStore represent correct create db store
func CreatePostgresDbStore() Store {
	store := PostgresDbStore{}
	if store.ExecMigration() {
		return &store
	}
	return nil
}

//PostgresDbStore represent main application data store
type PostgresDbStore struct {
}

//ExecMigration create all tables
func (s *PostgresDbStore) ExecMigration() (result bool) {
	db, err := sqlx.Connect("postgres", connStr)
	if err != nil {
		fmt.Println(err)
		return false
	}
	defer db.Close()
	db.MustExec(schema)
	return true
}

//Select represent select records from database
func (s *PostgresDbStore) Select(dest interface{}, query string) {
	db, err := sqlx.Connect("postgres", connStr)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
	db.Select(dest, query)
}
